# Commented sections are optional. Uncomment them if you want to include them in config

#publisher: # General publisher info section
#    author: # Author info
#    company: # Company info

# How to build and sign package
build:
    os: linux
    arch: x86
    sign_pkcs12: aos-user-sp.p12
    symlinks: copy
    # context: string, optional

# Information about publishing process (URI, cert, etc)
publish:
    url: aoscloud.io
    service_uid: 4fb6e632-3b88-4f3a-9119-0336067d76c2
    tls_pkcs12: aos-user-sp.p12

# Service configuration
configuration:

    # Startup command
    cmd: python3 -u /ramservice/ram_service.py -m 180 -host fakehost
    instances:
        minInstances: 1        # indicates minimal number of service's instances that should be run on Unit
        priority: 10            # Priority of service instance (0-1000000000, 0 is the lowest priority), default value is 0
        #labels:                # Labels where service instance should be run
        #    - gen3
    workingDir: / #service working directory

#    resources:
#        - system-dbus
#        - bluetooth


    quotas:
#        cpu: 50
        mem: 200MB        
#        state: 64KB
#        storage: 64KB
#        upload_speed: 32Kb
#        download_speed: 32Kb
#        upload: 1GB
#        download: 1GB
#        temp: 32KB
