# Commented sections are optional. Uncomment them if you want to include them in config

# How to build and sign package
build:
    os: linux
    arch: x86
    sign_pkcs12: aos-user-sp.p12
    symlinks: copy

# Information about publishing process (URI, cert, etc)
publish:
    url: aoscloud.io
    service_uid:
    tls_pkcs12: aos-user-sp.p12

# Service configuration
configuration:
    # Startup command
    cmd: python3 /telemetry_emulator/sender_vis_genivi.py
    # Service working dir
    workingDir: /
    resources:
        - vis
    #Quotas assigned to service
    quotas:
        cpu: 50
        mem: 100M
        #state: 64KB
        storage: 10M
        #upload_speed: 32Kb
        #download_speed: 32Kb
        #upload: 1GB
        #download: 1GB
        temp: 32KB
